### ISSUE TITLE
for some reason the Updates tab copies the latest actions

### ISSUE THREAD

**Issue by ghost** [hitman249/ProteWine#1]
for some reason the Updates tab copies the latest actions / почему то вкладка Updates копирует последние действия

Не знаю  как получилось воиспроизвести но что  то мне полсказывает ошбка гдето  в копоненте updates (прошу прошеня)

https://github.com/user-attachments/assets/93e214e3-227a-4411-8ded-ecea887db2be

**Comment by hitman249** [comment]
fixed in https://github.com/hitman249/ProteWine/releases/tag/1.0.5
